version: '3.8'
services:
  back-end:
    image: postgres:13
    ports:
    - 5432:5432
    environment:
      - POSTGRES_USER = postgres
      - POSTGRES_PASSWORD = 1347
      - POSTGRES_DB = nest-web